### ISSUE TITLE
info: ACL needed on the functions whenever proxy factory will get used

### ISSUE THREAD

**Issue by satyamakgec** [maple-labs/proxy-factory#4]
https://github.com/maple-labs/proxy-factory/blob/b18909327abfb86857d81a382a2a9f75931a95ff/contracts/ProxyFactory.sol#L21

Similar to the above we don't have the ACL in any of the functions so my fair assumption is whenever we are going to use that factory we will put access control over to those functions. Otherwise, anybody can register the implementation and upgrade as well.

**Comment by deluca-mike** [comment]
Correct. The inheritor of the `ProxyFactory` _can_, and _should_ override `registerImplementation` to modify ACL and other requirements. For example, out of the box, anyone can register a new implementation, but version identifiers cannot be reused, so you can use the versions you trust. One can override this so that not only can a factory owner control registering implementations, but that they could overwrite implementations by reusing version identifiers, or restrict the format of version identifiers.

**Comment by lucas-manuel** [comment]
Closing this issue - we should definitely make it abundantly clear that ACL is not present in the documentation.
